In [3]:
import pandas as pd
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("archive/blood_cell_anomaly_detection.csv")

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5880 entries, 0 to 5879
Data columns (total 36 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   cell_id                                  5880 non-null   object
 1   cell_type                                5880 non-null   object
 2   anomaly_label                            5880 non-null   int64
 3   disease_category                         5880 non-null   object
 4   cell_diameter_um                         5880 non-null   float64
 5   nucleus_area_pct                         5880 non-null   float64
 6   chromatin_density                        5880 non-null   float64
 7   cytoplasm_ratio                          5880 non-null   float64
 8   circularity                              5880 non-null   float64
 9   eccentricity                             5880 non-null   float64
 10  granularity_score                        5880 non-null   float64
 11  lobularity_score                         5880 non-null   float64
 12  membrane_smoothness                      5880 non-null   float64
 13  cell_area_px                             5880 non-null   int64
 14  perimeter_px                             5880 non-null   int64
 15  mean_r                                   5880 non-null   int64
 16  mean_g                                   5880 non-null   int64
 17  mean_b                                   5880 non-null   int64
 18  stain_intensity                          5880 non-null   float64
 19  patient_age_group                        5880 non-null   object
 20  patient_sex                              5880 non-null   object
 21  wbc_count_per_ul                         5880 non-null   int64
 22  rbc_count_millions_per_ul                5880 non-null   float64
 23  hemoglobin_g_dl                          5880 non-null   float64
 24  hematocrit_pct                           5880 non-null   float64
 25  platelet_count_per_ul                    5880 non-null   int64
 26  mcv_fl                                   5880 non-null   float64
 27  mchc_g_dl                                5880 non-null   float64
 28  dataset_source                           5880 non-null   object
 29  staining_protocol                        5880 non-null   object
 30  microscope_model                         5880 non-null   object
 31  magnification_x                          5880 non-null   int64
 32  image_resolution_px                      5880 non-null   int64
 33  cytodiffusion_anomaly_score              5880 non-null   float64
 34  cytodiffusion_classification_confidence  5880 non-null   float64
 35  labeller_confidence_score                5880 non-null   float64
dtypes: float64(18), int64(10), object(8)
memory usage: 1.6+ MB

In [7]:
df.describe()

,anomaly_label,cell_diameter_um,nucleus_area_pct,chromatin_density,cytoplasm_ratio,circularity,eccentricity,granularity_score,lobularity_score,membrane_smoothness,...,hemoglobin_g_dl,hematocrit_pct,platelet_count_per_ul,mcv_fl,mchc_g_dl,magnification_x,image_resolution_px,cytodiffusion_anomaly_score,cytodiffusion_classification_confidence,labeller_confidence_score
count,5880.000000,5880.000000,5880.000000,5880.000000,5880.000000,5880.000000,5880.000000,5880.000000,5880.000000,5880.000000,...,5880.000000,5880.000000,5880.000000,5880.000000,5880.000000,5880.000000,5880.000000,5880.000000,5880.000000,5880.000000
mean,0.319728,10.176267,43.537976,0.391394,0.564173,0.769263,0.365458,1.882109,1.769252,0.842866,...,13.547194,41.021956,249792.623469,88.942211,33.495867,76.006803,336.235374,0.317583,0.853243,0.866370
std,0.466411,3.642051,33.419390,0.310006,0.335282,0.158219,0.201501,1.428336,1.229362,0.096033,...,2.025136,5.484636,79472.676228,9.927005,1.480168,25.032178,111.922015,0.349655,0.106589,0.094065
min,0.000000,1.000000,0.000000,0.000000,0.050000,0.100000,0.000000,0.000000,1.000000,0.290000,...,5.400000,20.300000,20000.000000,60.000000,28.000000,40.000000,224.000000,0.000000,0.417300,0.471700
25%,0.000000,7.630000,0.000000,0.000000,0.276000,0.711000,0.214750,0.670000,1.000000,0.784000,...,12.200000,37.300000,194653.250000,82.300000,32.500000,60.000000,224.000000,0.063675,0.799000,0.817250
50%,0.000000,10.055000,54.500000,0.479500,0.452000,0.805000,0.331000,1.320000,1.000000,0.854000,...,13.500000,41.000000,250070.500000,88.900000,33.500000,100.000000,256.000000,0.113150,0.877450,0.883400
75%,1.000000,12.860000,72.300000,0.635000,1.000000,0.879000,0.456000,2.980000,2.300000,0.918000,...,14.900000,44.800000,303863.500000,95.700000,34.500000,100.000000,360.000000,0.743850,0.929350,0.934000
max,1.000000,21.180000,99.000000,1.000000,1.000000,1.000000,0.990000,6.000000,7.200000,1.000000,...,20.000000,60.000000,543084.000000,120.000000,38.000000,100.000000,512.000000,1.000000,1.000000,1.000000

In [8]:
print(f'Main dataset shape : {df.shape}')
print(f'Cell types         : {df.cell_type.nunique()}')
print(f'Normal cells       : {(df.anomaly_label==0).sum():,}')
print(f'Anomaly cells      : {(df.anomaly_label==1).sum():,}')
df.head()

Main dataset shape : (5880, 36)
Cell types         : 19
Normal cells       : 4,000
Anomaly cells      : 1,880

,cell_id,cell_type,anomaly_label,disease_category,cell_diameter_um,nucleus_area_pct,chromatin_density,cytoplasm_ratio,circularity,eccentricity,...,mcv_fl,mchc_g_dl,dataset_source,staining_protocol,microscope_model,magnification_x,image_resolution_px,cytodiffusion_anomaly_score,cytodiffusion_classification_confidence,labeller_confidence_score
0,CELL_005371,Hypersegmented_Neutrophil,1,Infection,15.18,58.8,0.542,0.301,0.563,0.529,...,85.5,31.4,CytoData,Giemsa,Zeiss_Axio,100,224,0.7649,0.5726,0.5670
1,CELL_005300,Hypersegmented_Neutrophil,1,Infection,16.47,73.6,0.583,0.365,0.859,0.443,...,92.5,35.0,PBC_Dataset,Wright,Zeiss_Axio,100,224,0.8472,0.7150,0.7273
2,CELL_000200,Neutrophil,0,Normal_WBC,13.41,55.5,0.448,0.376,0.781,0.407,...,76.3,33.0,CytoData,Wright,Leica_DM2000,100,512,0.0313,0.9225,0.9623
3,CELL_003269,Normal_RBC,0,Normal_RBC,7.36,0.0,0.000,1.000,0.880,0.167,...,92.3,32.5,CytoData,Wright,Leica_DM2000,100,512,0.1293,0.9180,0.8652
4,CELL_003505,Normal_RBC,0,Normal_RBC,7.53,0.0,0.000,1.000,1.000,0.158,...,83.9,33.4,CytoData,Wright,Olympus_BX51,100,224,0.1418,0.9697,0.8898